create table corpus (id bigint generated by default as identity, content varchar(255), name varchar(255), primary key (id));

create table resolved_corpus (resolved varchar(255), id bigint not null, primary key (id));

create table unqualified_corpus (reason varchar(255), id bigint not null, primary key (id));

alter table resolved_corpus add constraint FKqotxcxx8rp55ypjsllmxk12kj foreign key (id) references corpus on delete cascade;

alter table unqualified_corpus add constraint FKp7pn3s5av84ptd4e9rwypojvv foreign key (id) references corpus on delete no action;